name: 编译tunsafe

on:
  push:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  TZ: Asia/Shanghai
permissions:
  contents: write
  actions: write 
jobs:
  build:
    name: Build ${{ matrix.target }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - target: aarch64-linux
          URL: aarch64-linux-musl
          AARCH: arm64
          
        - target: x86_64-linux
          URL: x86_64-linux-musl
          AARCH: x86
        
        - target: armv7-linux-eabihf
          URL: armv7l-linux-musleabihf
          AARCH: arm

        - target: armv7-linux-eabi
          URL: armv7m-linux-musleabi
          AARCH: arm
          
        - target: arm-linux-eabihf
          URL: arm-linux-musleabihf
          AARCH: arm

        - target: arm-linux-eabi
          URL: arm-linux-musleabi
          AARCH: arm

        - target: mipsel-linux
          URL: mipsel-linux-muslsf
          AARCH: mips

        - target: mips-linux
          URL: mips-linux-muslsf
          AARCH: mips

    runs-on: ubuntu-latest
    steps:
     - name: Checkout code
       uses: actions/checkout@v4
       
     - name: 下载linux-musl-gcc
       uses: lmq8267/dl-musl@main
       with:
        target: ${{ matrix.URL }}
        static: true
        gccpath: /tmp
        
     - name: 编译
       run: |
         make ENABLE_STATIC=1 CROSS_PREFIX=${{ matrix.URL }}- ARCH=${{ matrix.AARCH }}
         echo "build_time=$(date '+%Y年%m月%d日%H:%M:%S' | jq -sRr @uri)" >> $GITHUB_ENV
         tagtime=$(date '+%Y-%m-%d')
         echo "tagtime=$(date '+%Y-%m-%d')" >> $GITHUB_ENV
         mv -f tunsafe tunsafe_${{ matrix.target }}
         
     - name: 安装 UPX
       uses: crazy-max/ghaction-upx@v3
       with:
        version: v4.2.4
        install-only: true
     - name: 压缩
       run: upx --lzma --best tunsafe 
        
     - uses: actions/upload-artifact@v4
       with:
        name: tunsafe-${{ matrix.target }}
        path: tunsafe_${{ matrix.target }}
        
     - name: 发布Release
       uses: softprops/action-gh-release@v2
       with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
           > ### ![](https://img.shields.io/badge/%E7%BC%96%E8%AF%91%E6%97%B6%E9%97%B4-${{ env.build_time }}-8267?logo=github&labelColor=%E9%A1%BB)![](https://img.shields.io/github/downloads/${{ github.repository }}/${{env.tagtime}}/total?label=%E4%B8%8B%E8%BD%BD%E6%AC%A1%E6%95%B0&logo=github) 
           
          tag_name: ${{env.tagtime}}
          files: tunsafe_${{ matrix.target }}
  del:
    runs-on: ubuntu-latest
    steps:
      - name: 删除流程记录
        if: github.event.inputs.del == 'true'
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          retain_days: 2
          keep_minimum_runs: 0
